# Generated by Django 4.2.6 on 2024-01-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='doctor_name',
            new_name='doctor_fname',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_lname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
