# Generated by Django 4.2.6 on 2024-01-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_rename_doctor_name_bookappointment_doctor_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='doctor_fname',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='doctor_lname',
        ),
    ]
